services:
  surrealdb:
    image: surrealdb/surrealdb:latest
    container_name: surrealdb
    ports:
      - "9900:8000"
    volumes:
      - /Users/jussmor/Developer/jussmor/upbase/mydata:/mydata
    command: start --log trace --auth --user root --pass root  file:/mydata/mydatabase.db
    restart: always
